package com.alfish.arealmvp.enums;

public enum AuthRejectReason {

	INCORRECT_EMAIL, INCORRECT_USERNAME, INCORRECT_PASSWORD,
	INVALID_TOKEN,
	INVALID_USERNAME, INVALID_PASSWORD, PASSWORDS_MISMATCH

}
